name: unique
baseurl: /unique
description: Functional Unique Values for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 2.0.0+30-b8bd35c3-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
