name: unique
baseurl: /unique
description: Functional Unique Values for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 1.0.0-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
