name: unique
baseurl: /unique
description: Functional Unique Values for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 2.0.0-RC2+17-febc1df8-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
