name: unique
baseurl: /unique
description: Functional Unique Values for Scala
highlighter: rouge
docs: true
collections:
  tut:
    output: true
version: 2.0.0+19-c7fc4c4c-SNAPSHOT
org: io.chrisdavenport
markdown: kramdown
